# Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Loading

In [ ]:
covid_19 = pd.read_csv('/content/drive/MyDrive/Datasets/covid_19_clean_complete.csv')

In [ ]:
covid_19

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

# Data cleaning and Preprocessing

In [ ]:
covid_19.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', 'Date', 'Confirmed',
       'Deaths', 'Recovered', 'Active', 'WHO Region'],
      dtype='object')

In [ ]:
covid_19['Province/State'].value_counts()

Province/State
Australian Capital Territory    188
New South Wales                 188
Northern Territory              188
Queensland                      188
South Australia                 188
                               ...
Anguilla                        188
British Virgin Islands          188
Turks and Caicos Islands        188
Falkland Islands (Malvinas)     188
Saint Pierre and Miquelon       188
Name: count, Length: 78, dtype: int64

In [ ]:
covid_19['Province/State'].nunique()

78

In [ ]:
covid_19['Country/Region'].value_counts()

Country/Region
China                    6204
Canada                   2256
France                   2068
United Kingdom           2068
Australia                1504
                         ...
Sao Tome and Principe     188
Yemen                     188
Comoros                   188
Tajikistan                188
Lesotho                   188
Name: count, Length: 187, dtype: int64

In [ ]:
covid_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [ ]:
covid_19.isnull().sum()

Province/State    34404
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
Deaths                0
Recovered             0
Active                0
WHO Region            0
dtype: int64

In [ ]:
covid_19['Province/State'] = covid_19['Province/State'].fillna(covid_19['Country/Region'])

In [ ]:
covid_19.isnull().sum()

Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64

In [ ]:
covid_19['Date'] = pd.to_datetime(covid_19['Date'])

In [ ]:
covid_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  49068 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  datetime64[ns]
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 3.7+ MB

# Filtering and grouping

In [ ]:
global_daily = (
    covid_19
    .groupby('Date')[['Confirmed','Deaths','Recovered','Active']]
    .sum()
    .reset_index()
    .sort_values('Date')
)
global_daily

          Date  Confirmed  Deaths  Recovered   Active
0   2020-01-22        555      17         28      510
1   2020-01-23        654      18         30      606
2   2020-01-24        941      26         36      879
3   2020-01-25       1434      42         39     1353
4   2020-01-26       2118      56         52     2010
..         ...        ...     ...        ...      ...
183 2020-07-23   15510481  633506    8710969  6166006
184 2020-07-24   15791645  639650    8939705  6212290
185 2020-07-25   16047190  644517    9158743  6243930
186 2020-07-26   16251796  648621    9293464  6309711
187 2020-07-27   16480485  654036    9468087  6358362

[188 rows x 5 columns]

In [ ]:
print(global_daily.shape)

(188, 5)

In [ ]:
country_daily = covid_19.groupby(['Date', 'Country/Region'])[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()
country_daily

            Date      Country/Region  Confirmed  Deaths  Recovered  Active
0     2020-01-22         Afghanistan          0       0          0       0
1     2020-01-22             Albania          0       0          0       0
2     2020-01-22             Algeria          0       0          0       0
3     2020-01-22             Andorra          0       0          0       0
4     2020-01-22              Angola          0       0          0       0
...          ...                 ...        ...     ...        ...     ...
35151 2020-07-27  West Bank and Gaza      10621      78       3752    6791
35152 2020-07-27      Western Sahara         10       1          8       1
35153 2020-07-27               Yemen       1691     483        833     375
35154 2020-07-27              Zambia       4552     140       2815    1597
35155 2020-07-27            Zimbabwe       2704      36        542    2126

[35156 rows x 6 columns]

# Visualization

In [ ]:
import plotly.express as px

In [ ]:
type(global_daily)

pandas.core.frame.DataFrame

In [ ]:
fig = px.line(
    global_daily,
    x = 'Date',
    y = ['Confirmed', 'Recovered', 'Deaths'],
    title='Global COVID-19 Trend',
    labels={'value': 'Number of Cases', 'variable': 'Category'}
)

fig.update_layout(template = 'plotly_white')
fig.show()

In [ ]:



country_daily = (
    covid_19.groupby(['Date', 'Country/Region'])[['Confirmed', 'Deaths', 'Recovered', 'Active']]
    .sum()
    .reset_index()
    .sort_values('Date')
)

latest_totals = country_daily[country_daily['Date'] == country_daily['Date'].max()]
top_countries = latest_totals.sort_values('Confirmed', ascending=False)['Country/Region'].head(10).tolist()

subset = country_daily[country_daily['Country/Region'].isin(top_countries)]


fig = px.line(
    subset,
    x='Date',
    y='Confirmed',
    color='Country/Region',
    title = f'Confirmed Cases in Top{len(top_countries)} Countries',
    labels={'Confirmed': 'Confirmed cases'}
)

fig.update_layout(template='plotly_white', legend_title='Country')
fig.show()

# Prediction using Prophet

In [ ]:
# Prediction using Facebook Prophet

! pip install prophet

Requirement already satisfied: prophet in /usr/local/lib/python3.12/dist-packages (1.2.1)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (1.3.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.0.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from prophet) (3.10.0)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.2.2)
Requirement already satisfied: holidays<1,>=0.25 in /usr/local/lib/python3.12/dist-packages (from prophet) (0.84)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from prophet) (4.67.1)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from prophet) (6.5.2)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (3.2.5)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->holidays<1,>=0.25->prophet) (1.17.0)

In [ ]:
from prophet import Prophet

In [ ]:
df_prophet = global_daily[['Date', 'Confirmed']].rename(columns={'Date':'ds', 'Confirmed': 'y'})

print(df_prophet.head())

          ds     y
0 2020-01-22   555
1 2020-01-23   654
2 2020-01-24   941
3 2020-01-25  1434
4 2020-01-26  2118

In [ ]:
# ! pip install --upgrade prophet

In [ ]:
combined_fig = make_subplots(rows=3, cols=1, subplot_titles=("Global Trend", "Top Countries", "Forecast"))

In [ ]:
future = m.make_future_dataframe(periods=7)
forecast = m.predict(future)

In [ ]:
from prophet.plot import plot_plotly

fig = plot_plotly(m, forecast)
fig.update_layout(title = 'COVID-19 Confirmed Case Forecast (Next 7 Days)',
                  xaxis_title = 'Date',
                  yaxis_title = 'Confirmed Cases')
fig.show()

In [ ]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from prophet.plot import plot_plotly

fig1 = px.line(
    global_daily,
    x='Date',
    y=['Confirmed', 'Recovered', 'Deaths'],
    title='Global COVID-19 Trend',
    labels={'value': 'Number of Cases', 'variable': 'Category'}
)
fig1.update_layout(template='plotly_white')

fig2 = plot_plotly(m, forecast)
fig2.update_layout(
    title='COVID-19 Confirmed Case Forecast (Next 7 Days)',
    xaxis_title='Date',
    yaxis_title='Confirmed Cases'
)


combined_fig = make_subplots(
    rows=2, cols=1,
    subplot_titles = ('Global Trend', '7-Day Forecast')
)

for trace in fig1.data:
  combined_fig.add_trace(trace, row=1, col=1)

for trace in fig2.data:
  combined_fig.add_trace(trace, row=2, col=1)

combined_fig.update_layout(
    height=900,
    title_text = 'COVID-19 Global Trend and Forecast',
    template = 'plotly_white'
)

combined_fig.show()